/* Append-only track record for the Genie. The daily task adds each card's picks here
   (status "pending"), then grades them after the fights: result win/loss + clv (closing
   line value %). Keep it honest — never delete a losing pick.

   ERA RESET 2026-07-23: the Genie switched to Kalshi-first pick selection (picks are now
   chosen by the live Kalshi price, not the sportsbook line). The old-era picks below in
   "archive" measured a different strategy, so the visible log restarts from this date.
   Nothing was deleted — the archive stays in this file for transparency. */
window.TRACK = {
  "since": "2026-07-23",
  "note": "We post every pick BEFORE the fights, then come back and mark whether it won or lost — and whether the odds moved our way afterward. Losses stay on the board forever. Nothing here is cherry-picked. (Log restarted 2026-07-23 when the Genie switched to picking by live Kalshi prices; earlier picks used the old sportsbook-edge logic and are archived, not erased.)",
  "historical": {
    "label": "Backtest — 99 fights, 8 cards (Jan–Mar 2026)",
    "accuracy": "78.8%",
    "roi": "+10.8%",
    "caveat": "Honest caveat: when asked to just pick winners, the Genie usually picks the favorite — and favorites win a lot anyway. So this number looks better than it really is, and it is NOT proof of an edge. It's here for transparency, not bragging. The live pick log above is the real test."
  },
  "picks": [
    {
      "date": "2026-07-23",
      "event": "UFC Fight Night: Ankalaev vs Guskov",
      "fighter": "Santiago Ponzinibbio",
      "div": "Welterweight (Prelim)",
      "odds": 320,
      "modelP": 0.5,
      "mktP": 0.229,
      "edge": 0.27,
      "kind": "Kalshi value pick (19¢, long shot — below 55% bar)",
      "result": "loss",
      "clv": -10.6
    },
    {
      "date": "2026-07-24",
      "event": "UFC Fight Night: Ankalaev vs Guskov",
      "fighter": "Ismael Bonfim",
      "div": "Lightweight (Prelim)",
      "odds": 160,
      "modelP": 0.481,
      "mktP": 0.369,
      "edge": 0.112,
      "kind": "parlay leg",
      "result": "loss",
      "clv": 0
    },
    {
      "date": "2026-07-24",
      "event": "UFC Fight Night: Ankalaev vs Guskov",
      "fighter": "Mike Davis",
      "div": "Lightweight (Prelim)",
      "odds": 190,
      "modelP": 0.364,
      "mktP": 0.331,
      "edge": 0.033,
      "kind": "parlay leg",
      "result": "loss",
      "clv": 0
    },
    {
      "date": "2026-07-24",
      "event": "UFC Fight Night: Ankalaev vs Guskov",
      "fighter": "Ramazan Temirov",
      "div": "Flyweight",
      "odds": -108,
      "modelP": 0.507,
      "mktP": 0.496,
      "edge": 0.012,
      "kind": "parlay leg",
      "result": "win",
      "clv": 0
    },
    {
      "date": "2026-07-25",
      "event": "UFC Fight Night: Medic vs Rodriguez",
      "fighter": "Ludovit Klein",
      "div": "Lightweight",
      "odds": -193,
      "modelP": 0.733,
      "mktP": 0.638,
      "edge": 0.095,
      "kind": "value pick + parlay leg (sportsbook edge — Kalshi not yet listed)",
      "result": "loss",
      "clv": 10.8
    },
    {
      "date": "2026-07-25",
      "event": "UFC Fight Night: Medic vs Rodriguez",
      "fighter": "Dusko Todorovic",
      "div": "Middleweight",
      "odds": 128,
      "modelP": 0.49,
      "mktP": 0.424,
      "edge": 0.066,
      "kind": "parlay leg",
      "result": "loss",
      "clv": -0.9
    },
    {
      "date": "2026-07-25",
      "event": "UFC Fight Night: Medic vs Rodriguez",
      "fighter": "Mateusz Rebecki",
      "div": "Lightweight (Prelim)",
      "odds": -335,
      "modelP": 0.772,
      "mktP": 0.743,
      "edge": 0.029,
      "kind": "parlay leg",
      "result": "win",
      "clv": 13.6
    },
    {
      "date": "2026-07-27",
      "event": "UFC Fight Night: Medic vs Rodriguez",
      "fighter": "Dennis Buzukja",
      "div": "Featherweight (Prelim)",
      "odds": 165,
      "modelP": 0.489,
      "mktP": 0.361,
      "edge": 0.128,
      "kind": "parlay leg",
      "result": "loss",
      "clv": 1.9
    },
    {
      "date": "2026-08-02",
      "event": "UFC Fight Night: Gamrot vs Salkilld",
      "fighter": "Diyar Nurgozhay",
      "div": "Light Heavyweight (Prelim)",
      "odds": -160,
      "modelP": 0.682,
      "mktP": 0.586,
      "edge": 0.096,
      "kind": "value pick + parlay leg (Kalshi 60¢, net edge ≈ +6.5 after fees)",
      "result": "win",
      "clv": -3.6
    },
    {
      "date": "2026-08-02",
      "event": "UFC Fight Night: Gamrot vs Salkilld",
      "fighter": "Billy Quarantillo",
      "div": "Lightweight",
      "odds": 135,
      "modelP": 0.526,
      "mktP": 0.403,
      "edge": 0.123,
      "kind": "parlay leg (Kalshi 40¢)",
      "result": "loss",
      "clv": -2.9
    },
    {
      "date": "2026-08-02",
      "event": "UFC Fight Night: Gamrot vs Salkilld",
      "fighter": "Mateusz Gamrot",
      "div": "Lightweight (Main Event)",
      "odds": 120,
      "modelP": 0.455,
      "mktP": 0.434,
      "edge": 0.021,
      "kind": "parlay leg (Kalshi 43¢)",
      "result": "loss",
      "clv": 0
    },
    {
      "date": "2026-08-03",
      "event": "UFC Fight Night: Gamrot vs Salkilld",
      "fighter": "Amanda Lemos",
      "div": "Women's Strawweight",
      "odds": 195,
      "modelP": 0.509,
      "mktP": 0.325,
      "edge": 0.184,
      "kind": "parlay leg (Kalshi 30¢ — big edge, treat with skepticism)",
      "result": "loss",
      "clv": -1
    },
    {
      "date": "2026-08-10",
      "event": "UFC 330: Makhachev vs Machado Garry",
      "fighter": "Gillian Robertson",
      "div": "Women's Strawweight Title",
      "odds": 223,
      "modelP": 0.583,
      "mktP": 0.307,
      "edge": 0.277,
      "kind": "value pick + parlay leg (Kalshi 32¢ — big edge, treat with skepticism)",
      "result": "loss",
      "clv": 16.2
    },
    {
      "date": "2026-08-10",
      "event": "UFC 330: Makhachev vs Machado Garry",
      "fighter": "Vicente Luque",
      "div": "Middleweight (Prelim)",
      "odds": 127,
      "modelP": 0.627,
      "mktP": 0.436,
      "edge": 0.191,
      "kind": "parlay leg (Kalshi 43¢ — big edge, treat with skepticism)",
      "result": "loss",
      "clv": 16.3
    },
    {
      "date": "2026-08-10",
      "event": "UFC 330: Makhachev vs Machado Garry",
      "fighter": "Donte Johnson",
      "div": "Middleweight (Prelim)",
      "odds": -240,
      "modelP": 0.802,
      "mktP": 0.678,
      "edge": 0.125,
      "kind": "parlay leg (Kalshi 68¢)",
      "result": "win",
      "clv": null
    },
    {
      "date": "2026-08-16",
      "event": "UFC Fight Night: Hernandez vs Rodrigues",
      "fighter": "Jackson McVey",
      "div": "Middleweight (Early Prelim)",
      "odds": -160,
      "modelP": 0.6474,
      "mktP": 0.6012,
      "edge": 4.6,
      "kind": "value pick + parlay leg (Kalshi 62¢)",
      "result": null,
      "clv": null
    },
    {
      "date": "2026-08-16",
      "event": "UFC Fight Night: Hernandez vs Rodrigues",
      "fighter": "MarQuel Mederos",
      "div": "Lightweight",
      "odds": 245,
      "modelP": 0.4984,
      "mktP": 0.2843,
      "edge": 21.4,
      "kind": "parlay leg (Kalshi 29¢ — big edge, treat with skepticism)",
      "result": null,
      "clv": null
    },
    {
      "date": "2026-08-16",
      "event": "UFC Fight Night: Hernandez vs Rodrigues",
      "fighter": "Serghei Spivac",
      "div": "Heavyweight",
      "odds": 142,
      "modelP": 0.4184,
      "mktP": 0.3962,
      "edge": 2.2,
      "kind": "parlay leg (Kalshi 41¢)",
      "result": null,
      "clv": null
    }
  ],
  "archive": {
    "label": "Old era (sportsbook-edge logic, retired 2026-07-23) — kept for transparency, not counted above",
    "picks": [
      {
        "date": "2026-06-27",
        "event": "UFC Fight Night 280",
        "fighter": "Manuel Torres",
        "div": "Lightweight (Main Event)",
        "odds": 115,
        "modelP": 0.642,
        "mktP": 0.45,
        "edge": 0.192,
        "kind": "value pick + parlay leg",
        "result": "loss",
        "clv": -6.5
      },
      {
        "date": "2026-06-27",
        "event": "UFC Fight Night 280",
        "fighter": "Charles Johnson",
        "div": "Flyweight",
        "odds": 180,
        "modelP": 0.425,
        "mktP": 0.345,
        "edge": 0.08,
        "kind": "parlay leg",
        "result": "loss",
        "clv": -18.8
      },
      {
        "date": "2026-06-27",
        "event": "UFC Fight Night 280",
        "fighter": "Michel Pereira",
        "div": "Middleweight (Co-Main)",
        "odds": 270,
        "modelP": 0.329,
        "mktP": 0.26,
        "edge": 0.069,
        "kind": "parlay leg",
        "result": "loss",
        "clv": -3.9
      },
      {
        "date": "2026-06-27",
        "event": "UFC Fight Night 280",
        "fighter": "Matheus Camilo",
        "div": "Lightweight",
        "odds": 217,
        "modelP": 0.419,
        "mktP": 0.314,
        "edge": 0.105,
        "kind": "parlay leg",
        "result": "win",
        "clv": 11.2
      },
      {
        "date": "2026-07-11",
        "event": "UFC 329",
        "fighter": "Conor McGregor",
        "div": "Welterweight (Main Event)",
        "odds": 180,
        "modelP": 0.504,
        "mktP": 0.336,
        "edge": 0.168,
        "kind": "value pick + parlay leg",
        "result": "loss",
        "clv": -16.4
      },
      {
        "date": "2026-07-11",
        "event": "UFC 329",
        "fighter": "Terrance McKinney",
        "div": "Lightweight",
        "odds": -190,
        "modelP": 0.768,
        "mktP": 0.63,
        "edge": 0.138,
        "kind": "parlay leg",
        "result": "loss",
        "clv": -22.2
      },
      {
        "date": "2026-07-11",
        "event": "UFC 329",
        "fighter": "Mario Bautista",
        "div": "Bantamweight",
        "odds": 125,
        "modelP": 0.527,
        "mktP": 0.426,
        "edge": 0.101,
        "kind": "parlay leg",
        "result": "win",
        "clv": 2.3
      },
      {
        "date": "2026-07-11",
        "event": "UFC 329",
        "fighter": "Benoit Saint Denis",
        "div": "Lightweight (Co-Main)",
        "odds": -148,
        "modelP": 0.632,
        "mktP": 0.572,
        "edge": 0.06,
        "kind": "parlay leg",
        "result": "loss",
        "clv": -7.9
      },
      {
        "date": "2026-07-18",
        "event": "UFC Fight Night: Du Plessis vs. Usman",
        "fighter": "Kamaru Usman",
        "div": "Middleweight (Main Event)",
        "odds": 225,
        "modelP": 0.437,
        "mktP": 0.292,
        "edge": 0.146,
        "kind": "value pick + parlay leg",
        "result": "loss",
        "clv": 23.6
      },
      {
        "date": "2026-07-18",
        "event": "UFC Fight Night: Du Plessis vs. Usman",
        "fighter": "Jared Cannonier",
        "div": "Middleweight (Co-Main)",
        "odds": 240,
        "modelP": 0.336,
        "mktP": 0.281,
        "edge": 0.055,
        "kind": "parlay leg",
        "result": "loss",
        "clv": -12.8
      },
      {
        "date": "2026-07-18",
        "event": "UFC Fight Night: Du Plessis vs. Usman",
        "fighter": "Mitch Ramirez",
        "div": "Lightweight",
        "odds": 240,
        "modelP": 0.307,
        "mktP": 0.281,
        "edge": 0.026,
        "kind": "parlay leg",
        "result": "loss",
        "clv": -11.7
      },
      {
        "date": "2026-07-18",
        "event": "UFC Fight Night: Du Plessis vs. Usman",
        "fighter": "Tommy McMillen",
        "div": "Featherweight",
        "odds": -112,
        "modelP": 0.59,
        "mktP": 0.5,
        "edge": 0.09,
        "kind": "parlay leg",
        "result": "win",
        "clv": 25.1
      },
      {
        "date": "2026-07-18",
        "event": "UFC Fight Night: Du Plessis vs. Usman",
        "fighter": "Tabatha Ricci",
        "div": "Women's Strawweight",
        "odds": 350,
        "modelP": 0.437,
        "mktP": 0.214,
        "edge": 0.224,
        "kind": "value pick + parlay leg",
        "result": "loss",
        "clv": -4.3
      },
      {
        "date": "2026-07-18",
        "event": "UFC Fight Night: Du Plessis vs. Usman",
        "fighter": "Stewart Nicoll",
        "div": "Flyweight (Prelim)",
        "odds": 700,
        "modelP": 0.358,
        "mktP": 0.12,
        "edge": 0.238,
        "kind": "value pick + parlay leg",
        "result": "loss",
        "clv": 0
      },
      {
        "date": "2026-07-18",
        "event": "UFC Fight Night: Du Plessis vs. Usman",
        "fighter": "Jean-Paul Lebosnoyani",
        "div": "Welterweight (Prelim)",
        "odds": 175,
        "modelP": 0.518,
        "mktP": 0.349,
        "edge": 0.169,
        "kind": "parlay leg",
        "result": "win",
        "clv": 10.9
      },
      {
        "date": "2026-07-18",
        "event": "UFC Fight Night: Du Plessis vs. Usman",
        "fighter": "Austin Bashi",
        "div": "Featherweight (Prelim)",
        "odds": -110,
        "modelP": 0.58,
        "mktP": 0.5,
        "edge": 0.08,
        "kind": "value pick + parlay leg",
        "result": "loss",
        "clv": 12.3
      },
      {
        "date": "2026-07-19",
        "event": "UFC Fight Night: Ankalaev vs Guskov",
        "fighter": "Nurullo Aliev",
        "div": "Lightweight (Prelim)",
        "odds": -159,
        "modelP": 0.636,
        "mktP": 0.583,
        "edge": 0.053,
        "kind": "value pick + parlay leg",
        "result": "win",
        "clv": 13.5
      },
      {
        "date": "2026-07-19",
        "event": "UFC Fight Night: Ankalaev vs Guskov",
        "fighter": "Ismael Bonfim",
        "div": "Lightweight",
        "odds": 145,
        "modelP": 0.481,
        "mktP": 0.387,
        "edge": 0.094,
        "kind": "parlay leg",
        "result": "loss",
        "clv": -5.8
      },
      {
        "date": "2026-07-19",
        "event": "UFC Fight Night: Ankalaev vs Guskov",
        "fighter": "Ramazan Temirov",
        "div": "Flyweight",
        "odds": -105,
        "modelP": 0.507,
        "mktP": 0.486,
        "edge": 0.021,
        "kind": "parlay leg",
        "result": "win",
        "clv": 1.4
      },
      {
        "date": "2026-07-20",
        "event": "UFC Fight Night: Ankalaev vs Guskov",
        "fighter": "Tyrell Fortune",
        "div": "Heavyweight",
        "odds": 215,
        "modelP": 0.424,
        "mktP": 0.302,
        "edge": 0.122,
        "kind": "parlay leg",
        "result": "loss",
        "clv": -14.9
      },
      {
        "date": "2026-07-20",
        "event": "UFC Fight Night: Ankalaev vs Guskov",
        "fighter": "Thomas Petersen",
        "div": "Heavyweight (Prelim)",
        "odds": 170,
        "modelP": 0.406,
        "mktP": 0.35,
        "edge": 0.056,
        "kind": "parlay leg",
        "result": "loss",
        "clv": 11.6
      },
      {
        "date": "2026-07-21",
        "event": "UFC Fight Night: Ankalaev vs Guskov",
        "fighter": "Mike Davis",
        "div": "Lightweight (Prelim)",
        "odds": 180,
        "modelP": 0.364,
        "mktP": 0.342,
        "edge": 0.022,
        "kind": "parlay leg",
        "result": "loss",
        "clv": -3.4
      },
      {
        "date": "2026-07-21",
        "event": "UFC Fight Night: Ankalaev vs Guskov",
        "fighter": "Damian Rzepecki",
        "div": "Lightweight",
        "odds": 260,
        "modelP": 0.55,
        "mktP": 0.271,
        "edge": 0.279,
        "kind": "value pick",
        "result": "loss",
        "clv": 4.3
      }
    ]
  }
};
